# Generated by Django 4.0.4 on 2022-04-18 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TopUpTransaction',
            fields=[
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('expense_type', models.TextField(choices=[('travel', 'Travel'), ('food', 'Food & Grocery'), ('phone', 'Cell Phone'), ('rent', 'Rent'), ('health', 'health & Insurance'), ('health', 'health & Insurance'), ('clothing', 'Clothing'), ('subscription', 'Subscription'), ('bill', 'bill'), ('other', 'other')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
