# Generated by Django 4.0.4 on 2022-04-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.TextField(choices=[('cash', 'Travel'), ('momo', 'Food & Grocery'), ('airtel', 'Cell Phone'), ('atm', 'Cell Phone'), ('bank', 'Cell Phone')], default='cash', max_length=30),
        ),
    ]
