# Generated by Django 4.0.4 on 2022-04-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.TextField(blank=True, choices=[('cash', 'Travel'), ('momo', 'Food & Grocery'), ('airtel', 'Cell Phone'), ('atm', 'Cell Phone'), ('bank', 'Cell Phone')], default='cash', max_length=30, null=True),
        ),
    ]
