# Generated by Django 4.0.4 on 2022-04-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('expenses', '0003_alter_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('momo', 'MTN MOMO'), ('airtel', 'Airtel Money'), ('Bank', 'Bank')], default='cash', max_length=30, null=True),
        ),
    ]
