# Generated by Django 4.0.4 on 2022-04-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_wallet_type_alter_wallet_owner_todoexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoexpense',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hign'), (2, 'Moderate'), (3, 'Low')], default=3),
        ),
    ]
