# Generated by Django 4.0.4 on 2022-04-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoexpense',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoexpense',
            name='date_expected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
