# Generated by Django 4.0.4 on 2022-04-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_todoexpense_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topuptransaction',
            options={'ordering': ['created']},
        ),
    ]
