# Generated by Django 4.0.4 on 2022-04-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_topuptransaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topuptransaction',
            options={'ordering': ['-created']},
        ),
    ]
